# Generated by Django 5.2.7 on 2026-01-07 06:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPNRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipn_id', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField()),
                ('ipn_notification_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_reference', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=8)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('correlation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('subscription_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.ipnregistration')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tracking_id', models.UUIDField(unique=True)),
                ('merchant_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_status_description', models.CharField(blank=True, max_length=128, null=True)),
                ('status_code', models.IntegerField(default=0)),
                ('payment_account', models.CharField(blank=True, max_length=64, null=True)),
                ('call_back_url', models.URLField(blank=True, null=True)),
                ('subscription_transaction_info', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tracking_id', models.UUIDField()),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('username', models.CharField(max_length=128)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymenttransaction')),
            ],
        ),
    ]
