# Generated by Django 5.2.6 on 2026-09-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('coffee_type', 'Coffee Type'), ('coffee_variety', 'Coffee Variety'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('standard_practice', 'Standard Practice'), ('seedling_type', 'Seedling Type'), ('grade', 'Grade'), ('spacing', 'Tree Spacing')], max_length=50)),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lookup Option',
                'verbose_name_plural': 'Lookup Options',
                'ordering': ['category', 'sort_order', 'value'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
