# Generated by Django 5.2.6 on 2026-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_coffeetype_farmasset_coffeesubtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('license', 'License'), ('certificate', 'Certificate'), ('contract', 'Contract'), ('audit', 'Audit Report'), ('other', 'Other')], default='certificate', max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expiry_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('trainer', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='lookupoption',
            name='category',
            field=models.CharField(choices=[('coffee_type', 'Coffee Type'), ('coffee_variety', 'Coffee Variety'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('standard_practice', 'Standard Practice'), ('seedling_type', 'Seedling Type'), ('grade', 'Grade'), ('spacing', 'Tree Spacing'), ('sale_item', 'Sale Item')], max_length=50),
        ),
    ]
