# Generated by Django 5.2.6 on 2025-10-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(help_text='Phone number used for login', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('manager', 'Farm Manager'), ('block_champion', 'Block Champion'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='block_champion', help_text="User's role in the system", max_length=20)),
                ('security_question', models.CharField(blank=True, help_text="Question for PIN reset (e.g., 'What is your mother's name?')", max_length=200)),
                ('_security_answer_hash', models.CharField(blank=True, help_text='Hashed security answer (never stored in plain text)', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='User can login if active')),
                ('is_staff', models.BooleanField(default=False, help_text='User can access Django admin')),
                ('is_superuser', models.BooleanField(default=False, help_text='User has all permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
