# Generated by Django 5.2.6 on 2025-10-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, help_text="User's full name", max_length=100
            ),
        ),
    ]
