# Generated by Django 5.2.6 on 2025-11-07 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The security question text",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable this question for new users",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Security Question",
                "verbose_name_plural": "Security Questions",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="security_answers_set",
            field=models.BooleanField(
                default=False,
                help_text="User has completed security questions setup on first login",
            ),
        ),
        migrations.CreateModel(
            name="UserSecurityAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_hash",
                    models.CharField(
                        help_text="Hashed answer (never store in plain text)",
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="The security question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.securityquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who answered the question",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Security Answer",
                "verbose_name_plural": "User Security Answers",
                "ordering": ["-created_at"],
                "unique_together": {("user", "question")},
            },
        ),
    ]
