# Generated by Django 5.2.6 on 2025-11-07 07:41

from django.db import migrations


def create_default_security_questions(apps, schema_editor):
    """Create the 5 predefined security questions."""
    SecurityQuestion = apps.get_model('users', 'SecurityQuestion')

    questions = [
        "What was your mother's clan name?",
        "What village were you born in?",
        "Which year did you start coffee farming?",
        "What was the first name of your favourite school teacher?",
        "Who is your favourite musician?",
    ]

    for question_text in questions:
        SecurityQuestion.objects.create(text=question_text, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_securityquestion_user_security_answers_set_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_security_questions),
    ]
