# Generated by Django 5.2.6 on 2025-11-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_securityquestion_user_security_answers_set_and_more"),
    ]

    operations = []
