# Generated by Django 5.2.6 on 2026-01-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financialmanagement", "0001_initial"),
        ("users", "0006_add_default_security_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to staff member if this user is also a staff member",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_account",
                to="financialmanagement.staff",
            ),
        ),
    ]
