# Generated by Django 5.2.6 on 2026-09-21 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Farm Manager'), ('block_champion', 'Block Champion'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], max_length=20)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('sales', 'Sales'), ('wages', 'Wages'), ('expenses', 'Expenses'), ('staff', 'Staff'), ('aggregation', 'Aggregation'), ('harvest', 'Harvest'), ('processing', 'Processing'), ('inventory', 'Inventory'), ('dispatch', 'Dispatch'), ('export', 'Export & Compliance'), ('settings', 'Settings'), ('tasks', 'Tasks')], max_length=30)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
