# Generated by Django 5.2.6 on 2025-10-13 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmerHarvest",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("weight_on_delivery", models.IntegerField(max_length=100, null=True)),
                (
                    "weight_after_floating",
                    models.IntegerField(max_length=100, null=True),
                ),
                ("date_of_delivery", models.CharField(max_length=100, null=True)),
                ("grade", models.CharField(max_length=100, null=True)),
                ("cherry_color", models.CharField(max_length=100, null=True)),
                ("stage", models.CharField(max_length=100, null=True)),
                ("amount_paid", models.CharField(max_length=100, null=True)),
                ("paid_by", models.CharField(max_length=100, null=True)),
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmerRegistration",
            fields=[
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                (
                    "nin",
                    models.CharField(
                        blank=True,
                        help_text="Enter 14 characters (A–Z, 0–9); leave empty if not available",
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NIN must be 14 characters: uppercase letters and digits only.",
                                regex="^[A-Z0-9]{14}$",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("farmer_type", models.CharField(max_length=15)),
                (
                    "started_coffee_farming_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Enter the year you started coffee farming (optional)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(2010)],
                    ),
                ),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "other_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sub_county", models.CharField(blank=True, max_length=100)),
                (
                    "other_sub_county",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("parish", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("gps_coordinates", models.CharField(blank=True, max_length=100)),
                ("nearest_landmark", models.CharField(blank=True, max_length=100)),
                (
                    "farmer_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("coffee_variety", models.CharField(max_length=100)),
                ("number_of_trees", models.PositiveIntegerField(default=0)),
                ("ownership_of_trees", models.BooleanField(default=True)),
                ("planted_date", models.DateField(blank=True, null=True)),
                ("land_ownership", models.CharField(max_length=100)),
                ("spacing_between_trees", models.CharField(max_length=100)),
                ("defforestation_status", models.BooleanField(default=True)),
                ("source_of_seedlings", models.CharField(max_length=100)),
                ("type_of_seedlings", models.CharField(max_length=100)),
                ("age_of_seedlings", models.CharField(max_length=100)),
                ("standard_practices", models.BooleanField(default=False)),
                ("irrigation_source", models.CharField(max_length=100)),
                ("fertilizers", models.CharField(max_length=100)),
                ("pesticide", models.CharField(max_length=100)),
            ],
        ),
    ]
