# Generated by Django 5.2.6 on 2025-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('num_trees', models.CharField(blank=True, default=0, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerHarvest',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('weight_note', models.CharField(blank=True, max_length=100)),
                ('date_of_delivery', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('cherry_color', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.CharField(blank=True, max_length=100)),
                ('paid_by', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
