# Generated by Django 5.2.6 on 2025-10-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmerharvest",
            name="weight_note",
        ),
        migrations.AddField(
            model_name="farmerharvest",
            name="weight_after_floating",
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farmerharvest",
            name="weight_on_delivery",
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="amount_paid",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="cherry_color",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="date_of_delivery",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="grade",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="paid_by",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="stage",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
