# Generated by Django 5.2.6 on 2025-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerharvest',
            name='weight_after_floating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmerharvest',
            name='weight_on_delivery',
            field=models.IntegerField(null=True),
        ),
    ]
