# Generated by Django 5.2.6 on 2025-09-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerharvest',
            name='harvest',
            field=models.CharField(max_length=100),
        ),
    ]
