# Generated by Django 5.2.6 on 2025-10-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerRegistration",
            fields=[
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("nin", models.CharField(blank=True, max_length=14, unique=True)),
                ("date_of_birth", models.DateField()),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "farmer_type",
                    models.CharField(
                        choices=[
                            ("COOPERATIVE", "Co-operative Farmer"),
                            ("INDIVIDUAL", "Individual Farmer"),
                        ],
                        max_length=15,
                    ),
                ),
                ("district", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("sub_county", models.CharField(blank=True, max_length=100)),
                ("parish", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("gps_coordinates", models.CharField(blank=True, max_length=100)),
                ("nearest_landmark", models.CharField(blank=True, max_length=100)),
                (
                    "farmer_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "coffee_variety",
                    models.CharField(
                        choices=[
                            ("ARABICA", "Arabica"),
                            ("ROBUSTA", "Robusta"),
                            ("LAIBERICA", "Laiberica"),
                        ]
                    ),
                ),
                ("number_of_trees", models.PositiveIntegerField(default=0)),
                ("ownership_of_trees", models.BooleanField(default=True)),
                ("planted_date", models.DateField()),
                (
                    "land_ownership",
                    models.CharField(
                        choices=[
                            ("FREEHOLD", "Freehold"),
                            ("MAILO", "Mailo"),
                            ("CUSTOMARY", "Customary"),
                            ("LEASEHOLD", "Leasehold"),
                        ]
                    ),
                ),
                ("spacing_between_trees", models.CharField(max_length=100)),
                ("defforestation_status", models.BooleanField(default=True)),
                (
                    "source_of_seedlings",
                    models.CharField(
                        choices=[
                            ("NURSERY", "Nursery"),
                            ("GOVERNMENT", "Government"),
                            ("CO-OPERATIVES", "Co-operatives"),
                            ("OTHER", "Other"),
                        ]
                    ),
                ),
                (
                    "type_of_seedlings",
                    models.CharField(
                        choices=[
                            ("ARABICA", "Arabica"),
                            ("ROBUSTA", "Robusta"),
                            ("LAIBERICA", "Laiberica"),
                        ]
                    ),
                ),
                ("age_of_seedlings", models.CharField(max_length=100)),
                (
                    "standard_practices",
                    models.BooleanField(
                        choices=[
                            ("BENDING", "Bending"),
                            ("PRUNING", "Pruning"),
                            ("WEEDING", "Weeding"),
                            ("STUMPING", "Stumping"),
                            ("STEMING", "Steming"),
                            ("MULCHING", "Mulching"),
                        ]
                    ),
                ),
                ("irrigation_source", models.CharField(max_length=100)),
                ("fertilizers", models.CharField(max_length=100)),
                ("pesticide", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Farmer",
        ),
        migrations.RemoveField(
            model_name="farmerharvest",
            name="weight_note",
        ),
        migrations.AddField(
            model_name="farmerharvest",
            name="weight_after_floating",
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farmerharvest",
            name="weight_on_delivery",
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="amount_paid",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="cherry_color",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="date_of_delivery",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="grade",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="paid_by",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="stage",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
