# Generated by Django 5.2.6 on 2025-10-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aggregation", "0002_alter_farmerharvest_weight_after_floating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmerregistration",
            name="other_district",
        ),
        migrations.RemoveField(
            model_name="farmerregistration",
            name="other_sub_county",
        ),
    ]
