# Generated by Django 5.2.6 on 2025-10-15 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregation", "0002_alter_farmerharvest_weight_after_floating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerregistration",
            name="fertilizers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="farmerregistration",
            name="pesticide",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
