# Generated by Django 5.2.6 on 2025-10-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0002_alter_farmerharvest_harvest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='contact_info',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='gender',
        ),
        migrations.AddField(
            model_name='farmer',
            name='num_trees',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
