# Generated by Django 5.2.6 on 2025-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0003_remove_farmerregistration_other_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerharvest',
            old_name='cherry_color',
            new_name='coffee_type',
        ),
        migrations.RenameField(
            model_name='farmerharvest',
            old_name='id',
            new_name='harvest_id',
        ),
        migrations.RenameField(
            model_name='farmerharvest',
            old_name='weight_after_floating',
            new_name='moisture_content',
        ),
        migrations.RemoveField(
            model_name='farmerharvest',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='farmerharvest',
            name='stage',
        ),
        migrations.AddField(
            model_name='farmerharvest',
            name='no_of_bags',
            field=models.IntegerField(null=True),
        ),
    ]
