# Generated by Django 5.2.6 on 2025-10-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0004_rename_cherry_color_farmerharvest_coffee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerharvest',
            name='moisture_content',
        ),
        migrations.RemoveField(
            model_name='farmerregistration',
            name='other_district',
        ),
        migrations.RemoveField(
            model_name='farmerregistration',
            name='other_sub_county',
        ),
        migrations.AddField(
            model_name='farmerharvest',
            name='price_per_kg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmerharvest',
            name='weight_on_delivery',
            field=models.IntegerField(null=True),
        ),
    ]
