# Generated by Django 5.2.6 on 2025-11-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0005_farmerharvest_price_per_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerharvest',
            name='no_of_bags',
        ),
        migrations.AddField(
            model_name='farmerharvest',
            name='location_of_delivery',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
