# Generated by Django 5.2.7 on 2025-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0006_remove_farmerharvest_no_of_bags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerharvest',
            name='gps_coordinates_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerharvest',
            name='location_of_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
