# Generated by Django 5.2.6 on 2025-11-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aggregation", "0002_remove_farmerregistration_other_district_and_more"),
        ("aggregation", "0007_farmerharvest_gps_coordinates_delivery_and_more"),
    ]

    operations = []
