# Generated by Django 5.2.6 on 2025-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregation", "0007_farmerharvest_gps_coordinates_delivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerharvest",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount paid to the farmer",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="date_of_delivery",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="farmerharvest",
            name="weight_on_delivery",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Weight of harvest in kg (2 decimal places)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
