# Generated by Django 5.2.7 on 2025-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0007_farmerharvest_gps_coordinates_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerregistration',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
