# Generated by Django 5.2.6 on 2025-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0008_alter_farmerharvest_amount_paid_and_more'),
    ]

    operations = [
        # Alter the field parameters (max_digits, etc.)
        migrations.AlterField(
            model_name='farmerharvest',
            name='amount_paid',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Amount paid to the farmer',
                max_digits=15,
                null=True
            ),
        ),
    ]
