# Generated by Django 5.2.7 on 2025-11-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0008_farmerregistration_qr_code'),
        ('aggregation', '0009_alter_farmerharvest_amount_paid'),
    ]

    operations = [
    ]
