# Generated by Django 5.2.6 on 2025-10-07 09:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_id', models.CharField(help_text='Unique ID for this bagging batch (e.g., BAG-2024-001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this batch', max_length=100)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], help_text='Quality grade of the coffee', max_length=1)),
                ('moisture_content', models.DecimalField(decimal_places=2, help_text='Final moisture content percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateField(help_text='Date when bagging occurred')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Final weight in kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bagging Process',
                'verbose_name_plural': 'Bagging Processes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Fermenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_id', models.CharField(help_text='Unique ID for this fermentation batch (e.g., FERM-2024-001)', max_length=50, unique=True)),
                ('days', models.PositiveIntegerField(help_text='Number of days for fermentation', validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(help_text='Descriptive name for this batch', max_length=100)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], help_text='Quality grade of the coffee', max_length=1)),
                ('cherry_colour', models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('Yellow', 'yellow'), ('Black', 'Black')], help_text='Cherry colour', max_length=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight_before', models.DecimalField(decimal_places=2, help_text='Weight in kg before fermentation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_after', models.DecimalField(decimal_places=2, help_text='Weight in kg after fermentation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fermenting Process',
                'verbose_name_plural': 'Fermenting Processes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sundrying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_id', models.CharField(editable=False, help_text='Auto-generated: DRY-{DDMMYY}-{SEQ}', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this batch', max_length=100)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], help_text='Quality grade of the coffee', max_length=1)),
                ('cherry_colour', models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black')], help_text='Cherry colour', max_length=10, null=True)),
                ('weather', models.CharField(choices=[('sunny', 'Sunny'), ('raining', 'Raining'), ('cloudy', 'Cloudy')], help_text='Weather conditions during drying', max_length=10)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5)),
                ('moisture_content', models.DecimalField(decimal_places=2, help_text='Moisture content percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight_before', models.DecimalField(decimal_places=2, help_text='Weight in kg before drying', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_after', models.DecimalField(decimal_places=2, help_text='Weight in kg after drying', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sundrying Process',
                'verbose_name_plural': 'Sundrying Processes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_id', models.CharField(editable=False, help_text='Auto-generated: WASH-{DDMMYY}-{SEQ}', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this batch', max_length=100)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], help_text='Quality grade of the coffee', max_length=1)),
                ('cherry_colour', models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black')], help_text='Cherry colour', max_length=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight_before', models.DecimalField(decimal_places=2, help_text='Weight in kg before washing', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_after', models.DecimalField(decimal_places=2, help_text='Weight in kg after washing', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Washing Process',
                'verbose_name_plural': 'Washing Processes',
                'ordering': ['-date'],
            },
        ),
    ]
