# Generated by Django 5.2.6 on 2025-09-29 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fermenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_id', models.CharField(help_text='Unique ID for this fermentation batch (e.g., FERM-2024-001)', max_length=50, unique=True)),
                ('days', models.PositiveIntegerField(help_text='Number of days for fermentation', validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(help_text='Descriptive name for this batch', max_length=100)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], help_text='Quality grade of the coffee', max_length=1)),
                ('date', models.DateField(help_text='Date when fermentation started')),
                ('weight_before', models.DecimalField(decimal_places=2, help_text='Weight in kg before fermentation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_after', models.DecimalField(decimal_places=2, help_text='Weight in kg after fermentation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fermenting Process',
                'verbose_name_plural': 'Fermenting Processes',
                'ordering': ['-date'],
            },
        ),
    ]
