# Generated by Django 5.2.6 on 2025-11-13 23:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drying",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processing_id",
                    models.CharField(
                        blank=True,
                        help_text="Processing ID - can only be used Mon-Sun (locked after week ends)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "lot_id",
                    models.CharField(
                        help_text="Auto-generated lot ID (W01-W52 based on ISO week)",
                        max_length=10,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of drying entry",
                    ),
                ),
                (
                    "weather_condition",
                    models.CharField(
                        blank=True,
                        help_text="Weather conditions (e.g., sunny, cloudy, drizzle)",
                        max_length=50,
                    ),
                ),
                (
                    "moisture_content",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current day's moisture percentage (%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current day's weight (kg)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "moisture_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous day's moisture for rate calculation. Auto-filled after day 1.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous day's weight for rate calculation. Auto-filled after day 1.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "processing_type",
                    models.CharField(
                        blank=True,
                        help_text="Auto-filled from processing_id (natural sundried, washed coffee, fermented)",
                        max_length=50,
                    ),
                ),
                (
                    "type_of_coffee",
                    models.CharField(
                        blank=True,
                        help_text="Auto-filled from processing_id on day 1, then locked for same processing_id",
                        max_length=50,
                    ),
                ),
                (
                    "days",
                    models.IntegerField(
                        blank=True,
                        help_text="Auto-generated: days since processing_id creation or lot start",
                        null=True,
                    ),
                ),
                (
                    "moisture_deviation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Auto-generated: moisture_content - 12 (ideal). E.g., +3 or -2",
                        max_digits=5,
                    ),
                ),
                (
                    "rate_of_drying",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Auto-generated: moisture_before - moisture_content",
                        max_digits=5,
                    ),
                ),
                (
                    "rate_of_weightloss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Auto-generated: weight_before - weight",
                        max_digits=10,
                    ),
                ),
                (
                    "outturn",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Auto-generated: percentage weight loss from first day",
                        max_digits=5,
                    ),
                ),
                (
                    "outturn_deviation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Auto-generated: outturn - 60 (target). E.g., +3 or -2",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Drying Record",
                "verbose_name_plural": "Daily Drying Records",
                "ordering": ["-date", "-lot_id"],
                "unique_together": {("lot_id", "date"), ("processing_id", "date")},
            },
        ),
        migrations.DeleteModel(
            name="Sundrying",
        ),
    ]
