# Generated by Django 5.2.6 on 2025-11-14 15:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_drying_delete_sundrying'),
        ('production', '0003_alter_harvests_block_id_alter_harvests_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ripeness',
            fields=[
                ('harvest', models.OneToOneField(help_text='Harvest batch being tested for ripeness', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ripeness_test', serialize=False, to='production.harvests')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date when ripeness test was performed')),
                ('sample_size', models.PositiveIntegerField(default=100, help_text='Total number of cherries in sample (default: 100)', validators=[django.core.validators.MinValueValidator(1)])),
                ('no_of_redcherry', models.PositiveIntegerField(help_text='Number of red cherries found in the sample', validators=[django.core.validators.MinValueValidator(0)])),
                ('ripeness_score', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: (no_of_redcherry / sample_size) * 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ripeness Test',
                'verbose_name_plural': 'Ripeness Tests',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Floating',
            fields=[
                ('grade_id', models.CharField(editable=False, help_text='Auto-generated: GR{A/B}{DDMM}{Letter}{00-99} (e.g., GRA1411A00)', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('grade', models.CharField(help_text='Grade classification (e.g., A for netweight, B for floaters)', max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg after floating test', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date when floating test was performed')),
                ('ripeness_score', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-filled from ripeness test of same harvest', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvest', models.ForeignKey(help_text='Harvest batch being tested for floating', on_delete=django.db.models.deletion.CASCADE, related_name='floating_tests', to='production.harvests')),
            ],
            options={
                'verbose_name': 'Floating Test',
                'verbose_name_plural': 'Floating Tests',
                'ordering': ['-date'],
            },
        ),
    ]
