# Generated by Django 5.2.6 on 2025-10-02 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0003_sundrying"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bagging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processing_id",
                    models.CharField(
                        help_text="Unique ID for this bagging batch (e.g., BAG-2024-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this batch", max_length=100
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[("A", "Grade A"), ("B", "Grade B"), ("C", "Grade C")],
                        help_text="Quality grade of the coffee",
                        max_length=1,
                    ),
                ),
                (
                    "moisture_content",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final moisture content percentage (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("date", models.DateField(help_text="Date when bagging occurred")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final weight in kg",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bagging Process",
                "verbose_name_plural": "Bagging Processes",
                "ordering": ["-date"],
            },
        ),
    ]
