# Generated by Django 5.2.6 on 2025-12-04 13:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0003_ripeness_floating"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaturalSundrying",
            fields=[
                (
                    "processing_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: SUND-{YYYYMMDD}-{SEQ}",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when sundrying started",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weight in kg before sundrying",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Natural Sundrying Process",
                "verbose_name_plural": "Natural Sundrying Processes",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="bagging",
            options={
                "ordering": ["-date"],
                "verbose_name": "Bagging Record",
                "verbose_name_plural": "Bagging Records",
            },
        ),
        migrations.AlterModelOptions(
            name="fermenting",
            options={
                "ordering": ["-end_date"],
                "verbose_name": "Fermenting Process",
                "verbose_name_plural": "Fermenting Processes",
            },
        ),
        migrations.RemoveField(
            model_name="bagging",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="bagging",
            name="name",
        ),
        migrations.RemoveField(
            model_name="bagging",
            name="processing_id",
        ),
        migrations.RemoveField(
            model_name="fermenting",
            name="cherry_colour",
        ),
        migrations.RemoveField(
            model_name="fermenting",
            name="date",
        ),
        migrations.RemoveField(
            model_name="fermenting",
            name="id",
        ),
        migrations.RemoveField(
            model_name="fermenting",
            name="name",
        ),
        migrations.RemoveField(
            model_name="fermenting",
            name="weight_after",
        ),
        migrations.RemoveField(
            model_name="fermenting",
            name="weight_before",
        ),
        migrations.RemoveField(
            model_name="washing",
            name="cherry_colour",
        ),
        migrations.RemoveField(
            model_name="washing",
            name="id",
        ),
        migrations.RemoveField(
            model_name="washing",
            name="name",
        ),
        migrations.RemoveField(
            model_name="washing",
            name="weight_after",
        ),
        migrations.RemoveField(
            model_name="washing",
            name="weight_before",
        ),
        migrations.AddField(
            model_name="bagging",
            name="expected_outturn",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Expected outturn (pulled from drying or computed during sync)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bagging",
            name="lot_id",
            field=models.CharField(
                db_index=True,
                default="W01",
                help_text="Lot id from drying (select existing drying lot_id)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="bagging",
            name="no_of_bags",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Total number of bags",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="bagging",
            name="outturn",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Measured outturn (pulled from drying or computed during sync)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bagging",
            name="qr_code",
            field=models.CharField(
                blank=True,
                help_text="QR code payload (which process / farmer / grade / harvest time) - leave blank until defined",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fermenting",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date when fermentation ended",
            ),
        ),
        migrations.AddField(
            model_name="fermenting",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date when fermentation started",
            ),
        ),
        migrations.AddField(
            model_name="fermenting",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Weight in kg after fermentation",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="washing",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Weight in kg after washing",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="bagging",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time when bagging was completed",
            ),
        ),
        migrations.AlterField(
            model_name="bagging",
            name="moisture_content",
            field=models.DecimalField(
                decimal_places=2,
                default=12.0,
                help_text="Moisture content percentage (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bagging",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                help_text="Weight in kilograms",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="drying",
            name="days",
            field=models.IntegerField(
                blank=True,
                help_text="Calculated on frontend: days since processing_id creation or lot start",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drying",
            name="moisture_deviation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Calculated on frontend: moisture_content - 12 (ideal)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drying",
            name="outturn",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Calculated on frontend: percentage weight loss from first day",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drying",
            name="outturn_deviation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Calculated on frontend: outturn - 60 (target)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drying",
            name="processing_type",
            field=models.CharField(
                blank=True,
                help_text="Calculated on frontend from processing_id (natural sundried, washed coffee, fermented)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drying",
            name="rate_of_drying",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Calculated on frontend: moisture_before - moisture_content",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drying",
            name="rate_of_weightloss",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Calculated on frontend: weight_before - weight",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drying",
            name="type_of_coffee",
            field=models.CharField(
                blank=True,
                help_text="Calculated on frontend from processing_id on day 1",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fermenting",
            name="days",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Number of days for fermentation (auto-calculated)",
            ),
        ),
        migrations.AlterField(
            model_name="fermenting",
            name="grade",
            field=models.ForeignKey(
                help_text="Grade ID from Floating quality control test",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fermenting_processes",
                to="processing.floating",
            ),
        ),
        migrations.AlterField(
            model_name="fermenting",
            name="processing_id",
            field=models.CharField(
                help_text="Frontend-generated: FER{DDMM}{SEQ} (e.g., FER041200)",
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="washing",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date when washing was performed",
            ),
        ),
        migrations.AlterField(
            model_name="washing",
            name="grade",
            field=models.ForeignKey(
                help_text="Grade ID from Floating quality control test",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="washing_processes",
                to="processing.floating",
            ),
        ),
        migrations.AlterField(
            model_name="washing",
            name="processing_id",
            field=models.CharField(
                editable=False,
                help_text="Auto-generated: WASH-{YYYYMMDD}-{SEQ}",
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="bagging",
            index=models.Index(fields=["-date"], name="processing__date_5cfc98_idx"),
        ),
        migrations.AddIndex(
            model_name="bagging",
            index=models.Index(fields=["lot_id"], name="processing__lot_id_d83376_idx"),
        ),
        migrations.AddField(
            model_name="naturalsundrying",
            name="grade",
            field=models.ForeignKey(
                help_text="Grade ID from Floating quality control test",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sundrying_processes",
                to="processing.floating",
            ),
        ),
    ]
