# Generated by Django 5.2.6 on 2025-12-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0004_naturalsundrying_alter_bagging_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "batch_id",
                    models.CharField(
                        help_text="Format: BA001, BA002, etc.",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "grade_ids",
                    models.JSONField(
                        help_text="Array of grade_ids included in this batch"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="User who created the batch", max_length=100
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the batch",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="fermenting",
            name="grade_ids",
            field=models.JSONField(
                default=list,
                help_text="Array of grade IDs being processed (can be single or multiple)",
            ),
        ),
        migrations.AddField(
            model_name="naturalsundrying",
            name="grade_ids",
            field=models.JSONField(
                default=list,
                help_text="Array of grade IDs being processed (can be single or multiple)",
            ),
        ),
        migrations.AddField(
            model_name="washing",
            name="grade_ids",
            field=models.JSONField(
                default=list,
                help_text="Array of grade IDs being processed (can be single or multiple)",
            ),
        ),
        migrations.AlterField(
            model_name="fermenting",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use grade_ids instead. Single grade ID from Floating quality control test",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fermenting_processes",
                to="processing.floating",
            ),
        ),
        migrations.AlterField(
            model_name="naturalsundrying",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use grade_ids instead",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sundrying_processes",
                to="processing.floating",
            ),
        ),
        migrations.AlterField(
            model_name="washing",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use grade_ids instead",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="washing_processes",
                to="processing.floating",
            ),
        ),
    ]
