# Generated by Django 5.2.6 on 2025-10-06 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_bagging'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermenting',
            name='cherry_colour',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('Yellow', 'yellow'), ('Black', 'Black')], help_text='Cherry colour', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sundrying',
            name='cherry_colour',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black')], help_text='Cherry colour', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='washing',
            name='cherry_colour',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black')], help_text='Cherry colour', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fermenting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sundrying',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sundrying',
            name='processing_id',
            field=models.CharField(editable=False, help_text='Auto-generated: DRY-{DDMMYY}-{SEQ}', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='washing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='washing',
            name='processing_id',
            field=models.CharField(editable=False, help_text='Auto-generated: WASH-{DDMMYY}-{SEQ}', max_length=50, unique=True),
        ),
    ]
