# Generated by Django 5.2.7 on 2026-01-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_batch_fermenting_grade_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermenting',
            name='processing_id',
            field=models.CharField(help_text='Frontend-generated: {BATCH_ID}-FER (e.g., BA001-FER)', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='floating',
            name='grade_id',
            field=models.CharField(help_text='Frontend-generated: {HARVEST_ID}-GR{A/B} (e.g., HV001-GRA, HV001-GRB)', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='naturalsundrying',
            name='processing_id',
            field=models.CharField(help_text='Frontend-generated: {BATCH_ID}-SUN (e.g., BA001-SUN)', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='washing',
            name='processing_id',
            field=models.CharField(help_text='Frontend-generated: {BATCH_ID}-WSH (e.g., BA001-WSH)', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
