# Generated by Django 5.2.6 on 2026-09-21 11:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_alter_fermenting_processing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floating',
            name='harvest',
            field=models.CharField(db_column='harvest_id', db_index=True, help_text='Harvest ID from either production or aggregation', max_length=50),
        ),
        migrations.AlterField(
            model_name='ripeness',
            name='harvest',
            field=models.CharField(db_column='harvest_id', help_text='Harvest ID from either production or aggregation', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Hulling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(db_index=True, help_text='Lot id from drying/bagging chain', max_length=100)),
                ('weight_before', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expecting_outturn', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('outturn', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=50)),
                ('activity', models.CharField(default='hulling', max_length=50)),
                ('custom_activity', models.CharField(blank=True, max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hulling Record',
                'verbose_name_plural': 'Hulling Records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='processing__date_6d33f5_idx'), models.Index(fields=['lot_id'], name='processing__lot_id_3ca2c2_idx')],
            },
        ),
    ]
