# taskmanagement/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

"""
URL patterns for the taskmanagement app.
All these URLs will be prefixed with /api/tasks/ in the main project urls.py

Available endpoints:

SEASONS:
- GET    /api/tasks/seasons/              → List all seasons
- POST   /api/tasks/seasons/              → Create new season
- GET    /api/tasks/seasons/{id}/         → Get specific season
- PUT    /api/tasks/seasons/{id}/         → Update season
- DELETE /api/tasks/seasons/{id}/         → Delete season
- GET    /api/tasks/seasons/current/      → Get currently active seasons
- GET    /api/tasks/seasons/upcoming/     → Get upcoming seasons
- GET    /api/tasks/seasons/{id}/tasks/   → Get all tasks for a season

TASKS:
- GET    /api/tasks/                      → List all tasks
- POST   /api/tasks/                      → Create new task
- GET    /api/tasks/{id}/                 → Get specific task
- PUT    /api/tasks/{id}/                 → Update task
- PATCH  /api/tasks/{id}/                 → Partial update task
- DELETE /api/tasks/{id}/                 → Delete task
- GET    /api/tasks/today/                → Get tasks for today
- GET    /api/tasks/upcoming/             → Get upcoming tasks (next 7 days)
- GET    /api/tasks/overdue/              → Get overdue tasks
- GET    /api/tasks/statistics/           → Get task statistics
- POST   /api/tasks/{id}/toggle_complete/ → Toggle task completion
- POST   /api/tasks/{id}/add_comment/     → Add comment to task

Query Parameters for Tasks:
- ?date=YYYY-MM-DD
- ?priority=low|medium|high
- ?completed=true|false
- ?block=<block_id>
"""

app_name = 'taskmanagement'

# Create a router for ViewSet-based views
router = DefaultRouter()
router.register(r'seasons', views.SeasonViewSet, basename='season')
router.register(r'', views.TaskViewSet, basename='task')

urlpatterns = [
    # Include all the routes generated by the router
    path('', include(router.urls)),
]
