# Generated by Django 5.2.7 on 2025-11-14 14:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when this tour is available')),
                ('time_slot', models.CharField(choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM')], help_text='Time slot for the tour', max_length=5)),
                ('available_spots', models.PositiveIntegerField(help_text='Number of spots available for this time slot')),
                ('is_available', models.BooleanField(default=True, help_text='Is this time slot still available for booking?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour Availability',
                'verbose_name_plural': 'Tour Availabilities',
                'ordering': ['date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tour package name (e.g., 'Coffee Farm Tour', 'Premium Experience')", max_length=200)),
                ('description', models.TextField(help_text="Detailed description of what's included in the tour")),
                ('duration', models.CharField(choices=[('1_hour', '1 Hour'), ('2_hours', '2 Hours'), ('half_day', 'Half Day (4 hours)'), ('full_day', 'Full Day (8 hours)')], default='2_hours', help_text='Duration of the tour', max_length=20)),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Price per person in your currency', max_digits=10)),
                ('max_group_size', models.PositiveIntegerField(default=20, help_text='Maximum number of people allowed per tour')),
                ('min_group_size', models.PositiveIntegerField(default=1, help_text='Minimum number of people required for the tour')),
                ('is_active', models.BooleanField(default=True, help_text='Is this tour package currently available for booking?')),
                ('includes', models.TextField(blank=True, help_text="What's included (refreshments, guide, transport, etc.)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, help_text='Unique booking reference number', max_length=20, unique=True)),
                ('customer_name', models.CharField(help_text='Full name of the person booking', max_length=200)),
                ('customer_email', models.EmailField(help_text='Email address for confirmation', max_length=254)),
                ('customer_phone', models.CharField(help_text='Phone number', max_length=20)),
                ('number_of_people', models.PositiveIntegerField(help_text='Number of people in the group', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or dietary requirements')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total cost for the booking', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to customer)')),
                ('is_paid', models.BooleanField(default=False, help_text='Has the customer paid?')),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('availability', models.ForeignKey(help_text='Selected date and time slot', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='farmtours.touravailability')),
                ('tour_package', models.ForeignKey(help_text='Selected tour package', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='farmtours.tourpackage')),
            ],
            options={
                'verbose_name': 'Tour Booking',
                'verbose_name_plural': 'Tour Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='touravailability',
            name='tour_package',
            field=models.ForeignKey(help_text='Which tour package this availability is for', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='farmtours.tourpackage'),
        ),
        migrations.AlterUniqueTogether(
            name='touravailability',
            unique_together={('tour_package', 'date', 'time_slot')},
        ),
    ]
