# Generated by Django 5.2.7 on 2025-11-17 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmtours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, help_text='Price per person for this tour package', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
