# Generated by Django 5.2.7 on 2025-11-17 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmtours', '0002_alter_tourpackage_price_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='number_of_people',
            field=models.PositiveIntegerField(help_text='Number of people in the group', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='tourbooking',
            unique_together={('customer_email', 'availability')},
        ),
    ]
