# Generated by Django 5.2.7 on 2025-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, help_text="Admin user's full name", max_length=100)),
                ('email', models.EmailField(help_text='Email address used for login', max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('manager', 'Manager')], default='admin', help_text="Admin user's role in the system", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Admin user can login if active')),
                ('is_staff', models.BooleanField(default=True, help_text='Admin user can access Django admin')),
                ('is_superuser', models.BooleanField(default=False, help_text='Admin user has all permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
