# Generated by Django 5.2.7 on 2025-11-14 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP has been verified')),
                ('is_used', models.BooleanField(default=False, help_text='Whether OTP has been used for password reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time (10 minutes from creation)')),
                ('admin_user', models.ForeignKey(help_text='Admin user requesting password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='adminuser.adminuser')),
            ],
            options={
                'verbose_name': 'Password Reset OTP',
                'verbose_name_plural': 'Password Reset OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
