# Generated by Django 5.2.7 on 2025-11-19 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Whether the admin user's email has been verified"),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique verification token', unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether email has been verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time (24 hours from creation)')),
                ('admin_user', models.ForeignKey(help_text='Admin user requesting email verification', on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to='adminuser.adminuser')),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
