# Generated by Django 5.2.6 on 2025-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=20)),
                ('days_worked', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_payment', models.DateField()),
                ('monthly_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('noted_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Wage Payment',
                'verbose_name_plural': 'Wage Payments',
                'ordering': ['-date_of_payment', 'employee_name'],
            },
        ),
    ]
