# Generated by Django 5.2.6 on 2025-10-13 09:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balancesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="Name of the account (e.g., 'Cash', 'Accounts Receivable', etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("A", "Asset"), ("L", "Liability"), ("E", "Equity")],
                        max_length=1,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="The current balance of this account.",
                        max_digits=15,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Account Balance",
                "verbose_name_plural": "Account Balances",
                "ordering": ["account_type", "account_type"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("item", models.CharField(max_length=50)),
                ("supplier", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=50)),
                ("batch_id", models.CharField(blank=True, max_length=20, null=True)),
                ("item", models.CharField(max_length=50)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_of_payment", models.DateField()),
                ("status", models.CharField(default="paid", max_length=20)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("method_of_payment", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Sale Record",
                "verbose_name_plural": "Sale Records",
                "ordering": ["-date_of_payment", "customer_name"],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=20, unique=True)),
                ("date_issued", models.DateField(auto_now_add=True)),
                ("is_voided", models.BooleanField(default=False)),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_info",
                        to="financialmanagement.sale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt",
                "verbose_name_plural": "Receipts",
                "ordering": ["-date_issued", "receipt_number"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated ID: RF + 3-digit number",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Staff member's first name", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Staff member's last name", max_length=100
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        help_text="National ID Number (unique identifier)",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NIN should contain only uppercase letters and numbers",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        help_text="District where staff member resides", max_length=100
                    ),
                ),
                (
                    "sub_county",
                    models.CharField(
                        help_text="Sub-county where staff member resides",
                        max_length=100,
                    ),
                ),
                (
                    "parish",
                    models.CharField(
                        help_text="Parish where staff member resides", max_length=100
                    ),
                ),
                (
                    "village",
                    models.CharField(
                        help_text="Village where staff member resides", max_length=100
                    ),
                ),
                (
                    "gender",
                    models.CharField(help_text="Gender of a worker", max_length=100),
                ),
                (
                    "date_hired",
                    models.DateField(help_text="Date when staff member was hired"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("fulltime", "Full Time"), ("parttime", "Part Time")],
                        default="fulltime",
                        help_text="Type of employment contract",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the staff member is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["nin"], name="financialma_nin_1b40e2_idx"),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="financialma_last_na_8db14a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Wage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_worked", models.IntegerField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_of_payment", models.DateField()),
                ("monthly_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "noted_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "employee_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wages",
                        to="financialmanagement.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wage Payment",
                "verbose_name_plural": "Wage Payments",
                "ordering": ["-date_of_payment", "employee_name__last_name"],
            },
        ),
    ]
