# Generated by Django 5.2.6 on 2025-10-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(help_text='Type of employment contract', max_length=100),
        ),
    ]
