# Generated by Django 5.2.6 on 2025-11-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
