# Generated by Django 5.2.6 on 2025-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0002_alter_sale_options_remove_sale_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_of_payment', 'customer_name'], 'verbose_name': 'Sale Record', 'verbose_name_plural': 'Sale Records'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='last_name',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
