# Generated by Django 5.2.6 on 2025-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0002_alter_sale_customer_name_alter_staff_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='amount_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wage',
            name='deduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wage',
            name='monthly_pay',
            field=models.IntegerField(),
        ),
    ]
