# Generated by Django 5.2.7 on 2025-10-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0002_alter_sale_customer_name_alter_staff_employment_type'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward: Rename the column from employee_name to employee_name_id
            sql="""
                ALTER TABLE financialmanagement_wage
                RENAME COLUMN employee_name TO employee_name_id;
            """,
            # Reverse: Rename it back if we need to rollback
            reverse_sql="""
                ALTER TABLE financialmanagement_wage
                RENAME COLUMN employee_name_id TO employee_name;
            """,
        ),
    ]
