# Generated by Django 5.2.7 on 2025-10-30 07:55

import django.db.models.deletion
from django.db import migrations, models


def migrate_employee_names(apps, schema_editor):
    """
    Migrate existing employee_name ForeignKey data to the new structure:
    - Copy ForeignKey ref to 'staff' field
    - Convert employee names to full text names in 'employee_name' field
    """
    # Use raw SQL to avoid Django ORM issues during migration
    with schema_editor.connection.cursor() as cursor:
        # Update employee_name_text with staff full names and copy staff_id
        cursor.execute("""
            UPDATE financialmanagement_wage w
            SET
                staff_id = w.employee_name_temp_id,
                employee_name_text = CONCAT(s.first_name, ' ', s.last_name)
            FROM financialmanagement_staff s
            WHERE w.employee_name_temp_id = s.staff_id;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0003_fix_wage_employee_name_column'),
    ]

    operations = [
        # Step 1: Rename old employee_name_id column to employee_name_temp_id
        migrations.RunSQL(
            sql="ALTER TABLE financialmanagement_wage RENAME COLUMN employee_name_id TO employee_name_temp_id;",
            reverse_sql="ALTER TABLE financialmanagement_wage RENAME COLUMN employee_name_temp_id TO employee_name_id;",
        ),

        # Step 2: Add new text field for employee_name
        migrations.AddField(
            model_name='wage',
            name='employee_name_text',
            field=models.CharField(blank=True, help_text='Employee name (can be any name)', max_length=255, null=True),
        ),

        # Step 3: Add staff ForeignKey field
        migrations.AddField(
            model_name='wage',
            name='staff',
            field=models.ForeignKey(
                blank=True,
                help_text='Link to registered staff member (optional)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='wages',
                to='financialmanagement.staff'
            ),
        ),

        # Step 4: Migrate data from old structure to new
        migrations.RunPython(migrate_employee_names, reverse_code=migrations.RunPython.noop),

        # Step 5: Drop the old temporary column
        migrations.RunSQL(
            sql="ALTER TABLE financialmanagement_wage DROP COLUMN employee_name_temp_id;",
            reverse_sql="ALTER TABLE financialmanagement_wage ADD COLUMN employee_name_temp_id VARCHAR(10);",
        ),

        # Step 6: Rename employee_name_text to employee_name
        migrations.RunSQL(
            sql="ALTER TABLE financialmanagement_wage RENAME COLUMN employee_name_text TO employee_name;",
            reverse_sql="ALTER TABLE financialmanagement_wage RENAME COLUMN employee_name TO employee_name_text;",
        ),

        # Step 7: Update Meta options
        migrations.AlterModelOptions(
            name='wage',
            options={
                'ordering': ['-date_of_payment'],
                'verbose_name': 'Wage Payment',
                'verbose_name_plural': 'Wage Payments'
            },
        ),
    ]
