# financialmanagement/migrations/0004_alter_wage_options_wage_created_at.py

# Generated by Django 5.2.6 on 2025-10-28 10:02
import datetime
# CORRECT IMPORT: The timezone module is now available as 'timezone'
from django.utils import timezone 
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0003_alter_wage_amount_paid_alter_wage_deduction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wage',
            options={'ordering': ['-date_of_payment', 'created_at'], 'verbose_name': 'Wage Payment', 'verbose_name_plural': 'Wage Payments'},
        ),
        migrations.AddField(
            model_name='wage',
            name='created_at',
            field=models.DateTimeField(
                # django.utils.timezone does not expose `utc` constant on all platforms/versions.
                # Use the stdlib datetime.timezone.utc to provide a tzinfo object.
                default=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                null=True, # Allow nulls temporarily
            ),
            preserve_default=False,
        ),
    ]