# Generated by Django 5.2.6 on 2025-10-02 20:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0003_accountbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text="Name of the account (e.g., 'Cash', 'Accounts Receivable', etc.)", max_length=100)),
                ('account_type', models.CharField(choices=[('A', 'Asset'), ('L', 'Liability'), ('E', 'Equity')], max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The current balance of this account.', max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Balance',
                'verbose_name_plural': 'Account Balances',
                'ordering': ['account_type', 'account_type'],
            },
        ),
        migrations.DeleteModel(
            name='AccountBalance',
        ),
    ]
