# Generated by Django 5.2.6 on 2025-10-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0003_expense'),
        ('financialmanagement', '0004_balancesheet_delete_accountbalance'),
    ]

    operations = [
    ]
