# Generated by Django 5.2.6 on 2025-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0004_alter_wage_options_wage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wage',
            name='employee_name',
            field=models.CharField(max_length=100),
        ),
    ]
