# Generated by Django 5.2.6 on 2025-10-28 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0005_alter_wage_created_at_alter_wage_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wages', to='financialmanagement.staff', verbose_name='Staff Member'),
        ),
    ]
