# Generated by Django 5.2.6 on 2025-10-12 20:55

import django.db.models.deletion
from django.db import migrations, models

import django.db.models.deletion
from django.db import migrations, models

# --- START: New Functions to Add ---

def convert_names_to_staff_ids(apps, schema_editor):
    """
    Looks up the staff member by name and updates the old wage field
    with the corresponding staff_id (the new foreign key value).
    """
    Wage = apps.get_model('financialmanagement', 'Wage')
    StaffRegistration = apps.get_model('financialmanagement', 'StaffRegistration')

    for wage in Wage.objects.all():
        # The old employee_name field holds the full name string
        full_name = wage.employee_name.strip()
        
        # Simple attempt to split name into first and last
        parts = full_name.split() 
        if not parts:
            continue # Skip records with empty names

        first_name = parts[0]
        last_name = parts[-1]
        
        try:
            # Try to find the staff member using their first and last name
            staff_member = StaffRegistration.objects.get(
                first_name=first_name, 
                last_name=last_name
            )
            
            # CRITICAL: Replace the name string with the staff_id
            # This is the value the ForeignKey conversion needs.
            wage.employee_name = staff_member.staff_id 
            wage.save()

        except StaffRegistration.DoesNotExist:
            # This handles the "Martha Sabano" error you saw.
            # You MUST manually handle or fix these records.
            print(f"\n--- WARNING ---")
            print(f"No matching StaffRegistration found for old wage record: {full_name}")
            print(f"To fix this, either create the staff member or delete the wage record in your database.")
            # We skip saving the wage record here to avoid potential corruption, 
            # but the migration process will still fail if there are records it can't fix.
            pass
            
def reverse_convert_names_to_staff_ids(apps, schema_editor):
    """
    A reverse operation that does nothing, as the conversion is irreversible.
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0005_merge_20251010_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('nin', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('district', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('parish', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('date_hired', models.DateField()),
                ('employment_type', models.CharField(max_length=20)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Staff Registration',
                'verbose_name_plural': 'Staff Registrations',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='batch_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(default='paid', max_length=20),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_info', to='financialmanagement.sale')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-date_issued', 'receipt_number'],
            },
        ),
        migrations.RunPython(convert_names_to_staff_ids, reverse_code=reverse_convert_names_to_staff_ids),
        migrations.AlterField(
            model_name='wage',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wages', to='financialmanagement.staffregistration'),
        ),
    ]
