# Generated by Django 5.2.6 on 2025-10-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financialmanagement", "0005_alter_wage_created_at_alter_wage_employee_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wage",
            options={
                "ordering": ["-date_of_payment"],
                "verbose_name": "Wage Payment",
                "verbose_name_plural": "Wage Payments",
            },
        ),
        migrations.AddField(
            model_name="wage",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to registered staff member (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wages",
                to="financialmanagement.staff",
            ),
        ),
        migrations.AlterField(
            model_name="wage",
            name="employee_name",
            field=models.CharField(
                blank=True,
                help_text="Employee name (can be any name)",
                max_length=255,
                null=True,
            ),
        ),
    ]
