# Generated by Django 5.2.6 on 2025-10-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0006_staffregistration_alter_wage_options_sale_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wage',
            options={'ordering': ['-date_of_payment', 'employee_name__last_name'], 'verbose_name': 'Wage Payment', 'verbose_name_plural': 'Wage Payments'},
        ),
    ]
