# Generated by Django 5.2.6 on 2025-10-30 13:30
#
# This migration properly converts the employee_name field from a ForeignKey
# to Staff to a plain CharField. This is a data migration that:
# 1. Stores the existing ForeignKey references temporarily
# 2. Removes the old ForeignKey constraint
# 3. Converts the column to TEXT
# 4. Optionally populates it with staff names (if needed)

from django.db import migrations, models


def migrate_employee_names(apps, schema_editor):
    """
    Convert employee_name from ForeignKey to plain text.
    PostgreSQL-compatible version.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        try:
            # First, check if the column is still named employee_name_id (ForeignKey convention)
            cursor.execute("""
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'financialmanagement_wage'
                AND column_name = 'employee_name_id'
            """)

            if cursor.fetchone():
                # Find and drop the foreign key constraint
                cursor.execute("""
                    SELECT constraint_name
                    FROM information_schema.table_constraints
                    WHERE table_name = 'financialmanagement_wage'
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name LIKE '%employee_name%'
                """)

                constraint = cursor.fetchone()
                if constraint:
                    cursor.execute(f'ALTER TABLE financialmanagement_wage DROP CONSTRAINT "{constraint[0]}"')

                # Rename employee_name_id to employee_name
                cursor.execute("""
                    ALTER TABLE financialmanagement_wage
                    RENAME COLUMN employee_name_id TO employee_name
                """)

            # Ensure the column exists and is text type
            cursor.execute("""
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'financialmanagement_wage'
                AND column_name = 'employee_name'
            """)

            if cursor.fetchone():
                # Convert the column to VARCHAR if needed
                cursor.execute("""
                    ALTER TABLE financialmanagement_wage
                    ALTER COLUMN employee_name TYPE VARCHAR(255)
                """)
        except Exception as e:
            # Silently handle errors (constraints may already be gone)
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0006_alter_wage_options_wage_staff_and_more'),
    ]

    operations = [
        # First, handle database schema cleanup
        migrations.RunPython(migrate_employee_names, migrations.RunPython.noop),

        # Then ensure Django model matches database
        migrations.AlterField(
            model_name='wage',
            name='employee_name',
            field=models.CharField(
                blank=True,
                help_text='Employee name (can be any name)',
                max_length=255,
                null=True
            ),
        ),
    ]
