# Generated by Django 5.2.6 on 2025-10-13 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financialmanagement", "0007_alter_wage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated ID: RF + 3-digit number",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Staff member's first name", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Staff member's last name", max_length=100
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        help_text="National ID Number (unique identifier)",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NIN should contain only uppercase letters and numbers",
                                regex="^[A-Z0-9]+$",
                            )
                        ],
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        help_text="District where staff member resides", max_length=100
                    ),
                ),
                (
                    "sub_county",
                    models.CharField(
                        help_text="Sub-county where staff member resides",
                        max_length=100,
                    ),
                ),
                (
                    "parish",
                    models.CharField(
                        help_text="Parish where staff member resides", max_length=100
                    ),
                ),
                (
                    "village",
                    models.CharField(
                        help_text="Village where staff member resides", max_length=100
                    ),
                ),
                (
                    "gender",
                    models.CharField(help_text="Gender of a worker", max_length=100),
                ),
                (
                    "date_hired",
                    models.DateField(help_text="Date when staff member was hired"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("fulltime", "Full Time"), ("parttime", "Part Time")],
                        default="fulltime",
                        help_text="Type of employment contract",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the staff member is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["nin"], name="financialma_nin_1b40e2_idx"),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="financialma_last_na_8db14a_idx",
                    ),
                ],
            },
        ),
    ]
