# Generated by Django 5.2.6 on 2025-10-30 13:45
#
# This migration removes the old foreign key constraint on employee_name
# that is no longer needed since employee_name is now a plain CharField.

from django.db import migrations


def remove_old_fk(apps, schema_editor):
    """
    Remove the old employee_name foreign key constraint.
    """
    from django.db import connection

    with connection.cursor() as cursor:
        try:
            # Find the foreign key constraint on employee_name
            cursor.execute("""
                SELECT constraint_name
                FROM information_schema.table_constraints
                WHERE table_name = 'financialmanagement_wage'
                AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%employee_name%'
            """)

            constraint = cursor.fetchone()
            if constraint:
                constraint_name = constraint[0]
                cursor.execute(f'ALTER TABLE financialmanagement_wage DROP CONSTRAINT "{constraint_name}"')
                print(f"✓ Dropped constraint: {constraint_name}")
            else:
                print("No employee_name foreign key constraint found")
        except Exception as e:
            print(f"Note: {e}")
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0007_convert_employee_name_to_text'),
    ]

    operations = [
        # Remove the old foreign key constraint
        migrations.RunPython(remove_old_fk, migrations.RunPython.noop),
    ]
