# Generated by Django 5.2.6 on 2025-11-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financialmanagement", "0008_remove_employee_name_fk_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setprice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_kgPrice", models.CharField(max_length=10)),
                ("farmer_kgPrice", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Price Setting",
                "verbose_name_plural": "Price Settings",
                "ordering": ["-id"],
            },
        ),
    ]
