# Generated by Django 5.2.6 on 2025-11-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0008_remove_employee_name_fk_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='monthly_salary',
            field=models.IntegerField(default=0),
        ),
    ]
