# Generated by Django 5.2.6 on 2025-11-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financialmanagement", "0002_alter_sale_customer_name"),
        ("financialmanagement", "0009_setprice"),
    ]

    operations = []
