# Generated by Django 5.2.7 on 2025-11-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0009_staff_monthly_salary'),
        ('financialmanagement', '0009_setprice'),
    ]

    operations = [
    ]
