# Generated by Django 5.2.7 on 2025-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0011_merge_20251107_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wage',
            name='days_worked',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='monthly_pay',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='noted_reason',
        ),
        migrations.AddField(
            model_name='wage',
            name='days_missed',
            field=models.IntegerField(default=0, help_text='Number of days a staff member missed'),
        ),
    ]
