# Generated by Django 5.2.7 on 2025-11-14 07:28

from django.db import migrations, models


def migrate_customer_names(apps, schema_editor):
    """
    Migrate existing customer_name data to first_name and last_name.
    Splits the name by the last space: everything before is first_name,
    everything after is last_name.
    """
    Sale = apps.get_model('financialmanagement', 'Sale')
    for sale in Sale.objects.all():
        if sale.customer_name:
            # Split by last space to separate first and last names
            name_parts = sale.customer_name.strip().rsplit(' ', 1)
            if len(name_parts) == 2:
                sale.first_name = name_parts[0]
                sale.last_name = name_parts[1]
            else:
                # If no space, put everything in last_name
                sale.first_name = ''
                sale.last_name = name_parts[0]
            sale.save()


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0012_update_wage_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_of_payment', 'last_name', 'first_name'], 'verbose_name': 'Sale Record', 'verbose_name_plural': 'Sale Records'},
        ),
        # Add new fields first
        migrations.AddField(
            model_name='sale',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Migrate data from customer_name to first_name and last_name
        migrations.RunPython(migrate_customer_names, migrations.RunPython.noop),
        # Remove old field after data migration
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
    ]
