# Generated by Django 5.2.6 on 2025-11-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financialmanagement", "0012_update_wage_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
