# Generated by Django 5.2.7 on 2025-11-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0013_alter_sale_options_remove_sale_customer_name_and_more'),
        ('financialmanagement', '0013_expense_quantity_expense_unit_cost'),
    ]

    operations = [
    ]
