# Generated by Django 5.2.7 on 2026-08-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialmanagement', '0014_merge_20251114_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
