# Generated by Django 5.2.6 on 2025-10-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Harvests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=100)),
                ("weight", models.CharField(max_length=100)),
                ("block", models.CharField(max_length=100)),
                ("cherry_color", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("amount_paid", models.CharField(max_length=100)),
            ],
        ),
    ]
