<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-07 10:21

=======
# Generated by Django 5.2.6 on 2025-10-13 06:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
>>>>>>> Edna
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> Edna
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Harvests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('cherry_color', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.CharField(blank=True, max_length=100)),
            ],
        ),
=======
            name="Harvests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=100)),
                ("weight", models.CharField(max_length=100)),
                ("block", models.CharField(max_length=100)),
                ("cherry_color", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("amount_paid", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "block_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "no_of_trees",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("date_planted", models.DateField()),
                ("type_of_coffee", models.CharField(max_length=100)),
                ("source_of_seedling", models.CharField(max_length=200)),
                ("type_of_seedling", models.CharField(max_length=200)),
                (
                    "age_of_seedling",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("use_pesticides", models.CharField(max_length=255)),
                ("pesticides_list", models.TextField(blank=True, null=True)),
                ("standard_practices", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
>>>>>>> Edna
    ]
