# Generated by Django 5.2.6 on 2025-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('block', models.CharField(blank=True, max_length=100)),
                ('cherry_color', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
