# Generated by Django 5.2.6 on 2025-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='fertilizer_names',
            field=models.TextField(blank=True, help_text='Comma-separated list of fertilizer names', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='fertilizers',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
