# Generated by Django 5.2.6 on 2025-10-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvests',
            name='amount_paid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='harvests',
            name='block',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='harvests',
            name='cherry_color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='harvests',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='harvests',
            name='grade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='harvests',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='harvests',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
