# Generated by Django 5.2.6 on 2025-10-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_block_fertilizer_names_block_fertilizers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harvests",
            name="block_id",
            field=models.CharField(
                help_text="Block identifier where coffee was harvested", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="harvests",
            name="paid_by",
            field=models.CharField(
                help_text="Staff member who processed the payment", max_length=100
            ),
        ),
    ]
