# Generated by Django 5.2.6 on 2025-12-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_alter_harvests_block_id_alter_harvests_paid_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harvests",
            name="harvest_id",
            field=models.CharField(
                help_text="Harvest ID: Frontend-generated (offline-first) or auto-generated by backend as fallback",
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
