# Generated by Django 5.2.6 on 2026-09-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockactivitylog',
            name='activity_scope',
            field=models.CharField(choices=[('block', 'Specific block'), ('farm', 'Whole farm / general'), ('nursery', 'Nursery'), ('processing', 'Processing area'), ('other', 'Other location')], default='block', max_length=20),
        ),
        migrations.AddField(
            model_name='blockactivitylog',
            name='location_label',
            field=models.CharField(blank=True, help_text='e.g. Main nursery, Fuel store', max_length=200),
        ),
        migrations.AlterField(
            model_name='blockactivitylog',
            name='block_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
