# Generated by Django 5.2.6 on 2026-09-21 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=50, unique=True)),
                ('batch_id', models.CharField(blank=True, max_length=50)),
                ('coffee_type', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bags', models.PositiveIntegerField(default=0)),
                ('moisture_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('dispatched', 'Dispatched'), ('sold', 'Sold')], default='in_stock', max_length=20)),
                ('source_harvest_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DispatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(max_length=30, unique=True)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_contact', models.CharField(blank=True, max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bags', models.PositiveIntegerField(default=0)),
                ('vehicle', models.CharField(blank=True, max_length=50)),
                ('driver', models.CharField(blank=True, max_length=120)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('dispatch_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='export_ops.inventorylot')),
            ],
            options={
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportTraceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=30, unique=True)),
                ('harvest_id', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('origin_gps', models.CharField(blank=True, max_length=100)),
                ('coffee_type', models.CharField(blank=True, max_length=100)),
                ('total_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trace_data', models.JSONField(blank=True, default=dict)),
                ('compliance_status', models.CharField(default='pending', max_length=30)),
                ('compliance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_records', to='export_ops.dispatchnote')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_records', to='export_ops.inventorylot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='export_ops.warehouse'),
        ),
    ]
