# Generated by Django 5.2.6 on 2025-12-13 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_alter_harvests_harvest_id"),
        ("taskmanagement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="taskmanagem_assigne_94c5d9_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="taskmanagem_due_dat_ef3733_idx",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="location",
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.AddField(
            model_name="task",
            name="activity",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of activity types"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="custom_activity",
            field=models.CharField(
                blank=True,
                help_text="Custom activity text when 'other' is selected",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date when task is scheduled",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="time",
            field=models.CharField(
                blank=True, help_text="Time of day (e.g., '2:30 PM')", max_length=50
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Convert existing integer FK values to a JSON array before changing the
                # column type to jsonb. The original schema used a ForeignKey so the
                # physical column in Postgres is `assigned_to_id`. To safely convert we:
                #  - drop the FK constraint if it exists,
                #  - rename `assigned_to_id` -> `assigned_to` (Django field name),
                #  - alter the column type to jsonb by wrapping the existing integer into
                #    a one-element array and converting to jsonb. This preserves existing
                #    assignments as an array [id].
                migrations.RunSQL(
                    # Use a plpgsql DO block to make the migration robust across Postgres
                    # versions and to handle cases where the original column may be
                    # `assigned_to_id` (FK) or already `assigned_to`.
                    sql=(
                        "DO $$\n"
                        "DECLARE c record;\n"
                        "BEGIN\n"
                        "  -- Ensure a jsonb 'assigned_to' column exists. If not, create it.\n"
                        "  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='taskmanagement_task' AND column_name='assigned_to') THEN\n"
                        "    ALTER TABLE taskmanagement_task ADD COLUMN assigned_to jsonb;\n"
                        "    -- If an integer FK column exists, populate the new jsonb column from it\n"
                        "    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='taskmanagement_task' AND column_name='assigned_to_id') THEN\n"
                        "      UPDATE taskmanagement_task SET assigned_to = to_jsonb(ARRAY[assigned_to_id]) WHERE assigned_to_id IS NOT NULL;\n"
                        "    END IF;\n"
                        "    ALTER TABLE taskmanagement_task ALTER COLUMN assigned_to SET DEFAULT '[]'::jsonb;\n"
                        "  END IF;\n"
                        "\n"
                        "  -- If the old FK column exists, drop any FK constraints referencing it and then drop the column.\n"
                        "  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='taskmanagement_task' AND column_name='assigned_to_id') THEN\n"
                        "    -- Drop FK constraints regardless of their exact names\n"
                        "    FOR c IN SELECT pc.conname FROM pg_constraint pc\n"
                        "      JOIN pg_class cl ON pc.conrelid = cl.oid\n"
                        "      JOIN unnest(pc.conkey) WITH ORDINALITY AS cols(attnum, idx) ON true\n"
                        "      JOIN pg_attribute a ON a.attrelid = cl.oid AND a.attnum = cols.attnum\n"
                        "      WHERE cl.relname = 'taskmanagement_task' AND a.attname = 'assigned_to_id' AND pc.contype = 'f'\n"
                        "    LOOP\n"
                        "      EXECUTE format('ALTER TABLE taskmanagement_task DROP CONSTRAINT %I', c.conname);\n"
                        "    END LOOP;\n"
                        "    -- Finally drop the old FK column\n"
                        "    ALTER TABLE taskmanagement_task DROP COLUMN assigned_to_id;\n"
                        "  END IF;\n"
                        "END$$;"
                    ),
                    reverse_sql=(
                        "DO $$\n"
                        "BEGIN\n"
                        "  -- Try to convert jsonb array back to bigint and rename column back if needed\n"
                        "  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'taskmanagement_task' AND column_name = 'assigned_to') THEN\n"
                        "    BEGIN\n"
                        "      EXECUTE 'ALTER TABLE taskmanagement_task ALTER COLUMN assigned_to TYPE bigint USING ((assigned_to->>0)::bigint)';\n"
                        "    EXCEPTION WHEN others THEN\n"
                        "      RAISE NOTICE 'Skipping reverse assigned_to conversion: %', SQLERRM;\n"
                        "    END;\n"
                        "    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'taskmanagement_task' AND column_name = 'assigned_to') THEN\n"
                        "      EXECUTE 'ALTER TABLE taskmanagement_task RENAME COLUMN assigned_to TO assigned_to_id';\n"
                        "    END IF;\n"
                        "  END IF;\n"
                        "END$$;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="task",
                    name="assigned_to",
                    field=models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of staff IDs assigned to this task",
                    ),
                ),
            ]
        ),
        migrations.AlterField(
            model_name="task",
            name="block",
            field=models.ForeignKey(
                blank=True,
                help_text="Farm block where this task is to be performed",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="production.block",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Farm Manager or Block Champion who created the task",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(blank=True, default="medium", max_length=50),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["date", "completed"], name="taskmanagem_date_f035a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["created_at"], name="taskmanagem_created_9156ac_idx"
            ),
        ),
    ]
