# Generated by Django 5.2.6 on 2025-12-13 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_alter_harvests_harvest_id"),
        ("taskmanagement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="taskmanagem_assigne_94c5d9_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="taskmanagem_due_dat_ef3733_idx",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="location",
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.AddField(
            model_name="task",
            name="activity",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of activity types"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="custom_activity",
            field=models.CharField(
                blank=True,
                help_text="Custom activity text when 'other' is selected",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date when task is scheduled",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="time",
            field=models.CharField(
                blank=True, help_text="Time of day (e.g., '2:30 PM')", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of staff IDs assigned to this task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="block",
            field=models.ForeignKey(
                blank=True,
                help_text="Farm block where this task is to be performed",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="production.block",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Farm Manager or Block Champion who created the task",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(blank=True, default="medium", max_length=50),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["date", "completed"], name="taskmanagem_date_f035a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["created_at"], name="taskmanagem_created_9156ac_idx"
            ),
        ),
    ]
