# Generated by Django 5.2.6 on 2025-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='harvest',
            fields=[
                ('cherry_color', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_harvest', models.CharField(max_length=100)),
                ('quantity_harvest', models.CharField(max_length=200)),
                ('crop_type', models.CharField(max_length=100)),
                ('block', models.DateField()),
            ],
        ),
    ]
