# Generated by Django 5.2.6 on 2025-09-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='harvest',
            new_name='Harvests',
        ),
    ]
