"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


import os
from pathlib import Path
try:
    import dj_database_url
except ImportError:
    dj_database_url = None
from datetime import timedelta
from decouple import config
from dotenv import load_dotenv

import os

PESAPAL_CONSUMER_KEY = os.getenv("PESAPAL_CONSUMER_KEY")
PESAPAL_CONSUMER_SECRET = os.getenv("PESAPAL_CONSUMER_SECRET")
PESAPAL_BASE_URL = os.getenv("PESAPAL_BASE_URL")
PESAPAL_IPN_ID = os.getenv("PESAPAL_IPN_ID")


print("PESAPAL BASE URL:", PESAPAL_BASE_URL)


load_dotenv()
import environ



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default='django-insecure-fallback-key-change-in-production')



# SECURITY WARNING: don't run with debug turned on in production
# SECURITY WARNING: don't run with debug turned on in production
DEBUG = config('DEBUG', default=True, cast=bool) 

allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [
    host.strip()
    for host in allowed_hosts_env.split(',')
    if host.strip()
] or ['127.0.0.1', 'localhost', '192.168.100.2', '192.168.1.95']

render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_hostname and render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_hostname)

if not DEBUG and '.onrender.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.onrender.com')

CSRF_TRUSTED_ORIGINS = [
    f'https://{host}' for host in ALLOWED_HOSTS
    if host and not host.startswith('.') and host not in ('127.0.0.1', 'localhost')
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "drf_spectacular",
    "financialmanagement",
    'aggregation',
    'production',
    "processing",
    "users",
    "adminuser",
    "taskmanagement",
    'activities',
    'farmtours',
    'payments',
    'configuration',
    'export_ops',
    'field_ops',

]

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'users.backends.PhonePinBackend',        # Phone/PIN authentication for mobile users
    'adminuser.backends.EmailPasswordBackend',  # Email/Password authentication for admin users
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "activities.middleware.CurrentUserMiddleware",  # Track current user for activity logging
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    # Use JWT for authentication by default
    'DEFAULT_AUTHENTICATION_CLASSES': [
       'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    # Require authentication by default (except views with AllowAny)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
        #'rest_framework.permissions.IsAuthenticated'
    ],
    
    # Use JSON renderer (standard for APIs)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    
    # Pagination (optional, useful for large datasets)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

REST_FRAMEWORK['DEFAULT_SCHEMA_CLASS'] = 'drf_spectacular.openapi.AutoSchema'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Farm Management API',
    'DESCRIPTION': 'API for farm management system',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [
        {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    ],
    'SECURITY_REQUIREMENTS': [
        {
            'Bearer': []
        }
    ],
    'ENUM_NAME_OVERRIDES': {
        'CherryColour051Enum': 'CherryColourEnum',
    },
}

# ============================================
# JWT CONFIGURATION
# ============================================
SIMPLE_JWT = {
    # Access token expires after 24 hours (adjust as needed)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    
    # Refresh token expires after 7 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # Rotate refresh tokens (get new refresh token when refreshing)
    'ROTATE_REFRESH_TOKENS': True,
    
    # Blacklist old tokens (requires simplejwt.token_blacklist app)
    'BLACKLIST_AFTER_ROTATION': False,  # Set to True if you add token blacklist
    
    # Algorithm for signing tokens
    'ALGORITHM': 'HS256',
    
    # User ID field
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    # Token type
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ============================================
# CORS CONFIGURATION
# ============================================
# Allow React web app and React Native app to make requests

# For development - allow all origins
CORS_ALLOW_ALL_ORIGINS = True  # Change to False in production!

# For production - specify allowed origins
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",           # React web app (development)
#     "http://localhost:19006",          # React Native (Expo)
#     "https://yourproduction.com",      # Production web app
# ]

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allow these HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow these headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.static",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"




# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Try to use DATABASE_URL if available (for Render), otherwise use individual settings
database_url = (
    os.getenv("DATABASE_URL")
    or os.getenv("DB_URL")
    or env("DATABASE_URL", default=None)
    or env("DB_URL", default=None)
)
if database_url:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            ssl_require="render.com" in database_url,
        )
    }
elif env("DB_NAME", default=None):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER", default="postgres"),
            "PASSWORD": env("DB_PASSWORD", default="postgres"),
            "HOST": env("DB_HOST", default="localhost"),
            "PORT": env("DB_PORT", default="5432"),
        }
    }
else:
    # Fallback for build/collectstatic when DB env vars are not injected yet
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "build.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files (User uploads - photos, documents, etc.)
# For demo: stored on droplet. Migrate to AWS S3 for production.
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================
# EMAIL CONFIGURATION
# ============================================
# Email backend for sending OTP emails
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')

# SMTP settings (for production)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@farmmanagement.com')

# For development: emails will be printed to console
# For production: configure SMTP settings in .env file

# LOGGING (Optional but helpful for debugging)
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# ============================================
# NOTES FOR PRODUCTION
# ============================================
"""
Before deploying to production:

1. Set DEBUG = False
2. Update ALLOWED_HOSTS with your domain
3. Set CORS_ALLOW_ALL_ORIGINS = False
4. Specify exact CORS_ALLOWED_ORIGINS
5. Use environment variables for SECRET_KEY
6. Configure HTTPS
7. Set secure cookie settings:
   - SESSION_COOKIE_SECURE = True
   - CSRF_COOKIE_SECURE = True
8. Consider adding rate limiting
"""

# ============================================
# MEDIA FILES CONFIGURATION
# ============================================
# Media files (User uploads - photos, documents, etc.)
# For demo: stored on droplet at /media/. Migrate to AWS S3 for production.
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
